### ISSUE TITLE
Does Not Support Options or Variables in YML

### ISSUE THREAD

**Issue by kling-appfire** [serverless-components/website#14]
Please update to support CL options and ${property.variables}

**Comment by eahefnawy** [comment]
YAML references should work 🤔 ... have you tried that?

```
service: files

images:
  component: "@serverless/aws-s3"
  inputs:
    name: ${service}-images

```

Regarding CLI, we currently don't support it so that we don't tie the template to the CLI. Remember that unlike the framework, components could be used programmatically as well.
