### ISSUE TITLE
Allow configurable bucket

### ISSUE THREAD

**Issue by martrik** [serverless-components/website#2]
The name of the bucket used to store the static files is saved in the `.serverless` folder, which isn't supposed to be included in source control. Therefore, every time a new version of a website is deployed from a machine that doesn't contain that folder (CD/CI pipeline for instance), the component creates a new bucket where it uploads the website. This isn't ideal in some cases, especially since old buckets aren't automatically removed. Therefore, I believe it would make sense to let people pass the name of a concrete bucket to the component through an input parameter (same as `region` for instance).

I've got a fork of the component with that change made, and I'd be more than happy to submit a PR if you agree with the proposed solution.

**Comment by Durgaprasad-Budhwani** [comment]
Agree with @martrik, we need to configure bucket name. Please refer PR https://github.com/serverless-components/website/pull/3

It has an optional property `bucketName`. If provided, it will use that bucket, if not provided, it will create random bucket name. 

### Example

```yaml
myWebsite:
  component: "@serverless/website"
  inputs:
    bucketName: myBucket # (Optional) The Bucket name where `src` files/folder will be upload.
                         # If not provided, it will create random bucket name and upload

```
