### ISSUE TITLE
Ability to override IndexDocument and ErrorDocument

### ISSUE THREAD

**Issue by uxtx** [serverless-components/website#28]
for a project I'm working on we discovered it'd be desirable to override the indexDocument and errorDocument - and would be great to be able to specify the desired override in the serverless.yml/serverless.js configuration, eg, something like: 

```
# serverless.yml

name: my-website
stage: dev

myWebsite:
  component: "@serverless/website"
  inputs:
    code:
      root: ./ # The root folder of your website project.  Defaults to current working directory
      src: ./src # The folder to be uploaded containing your built artifact
      hook: npm run build # A hook to build/test/do anything to your code before uploading
    region: us-east-1 # The AWS region to deploy your website into
    bucketName: myBucket # (Optional) The Bucket name where `src` files/folder will be upload. 
                         # If not provided, it will create random bucket name and upload `src` files
    env: # Environment variables to include in a 'env.js' file with your uploaded code.
      API_URL: https://api.com

    ### NEW PROPERTIES HERE
    indexDocument: index.html # (Optional) the default page for your website
    errorDocument: index.html # (Optional) the error page for your website.
    ### END NEW PROPERTIES


    # You can specify a custom domain name for your website.
    # You must have a public hosted zone available for this domain in AWS Route53.
    # This is done automatically for you if you've purchased the domain via AWS Route53.
    domain: www.example.com
```
Any chance I could submit a patch to this project to enable this functionality?
