### ISSUE TITLE
Unsupported AWS ACM Certificate status

### ISSUE THREAD

**Issue by shadrech** [serverless-components/website#34]
I keep getting this error:
```
Error: Your AWS ACM Certificate for the domain "domain.com" has an unsupported status of: "VALIDATION_TIMED_OUT".  Please remove it manually and deploy again.
```

My serverless.yml is like
```
name: website

website:
  component: '@serverless/website'
  inputs:
    code:
      src: build
      hook: yarn build
    domain: sub.domain.com
    region: eu-west-1
```

Maybe is there an issue with giving a site a subdomain?
