### ISSUE TITLE
domain configuration fails on tlds with multiple dots (eg: example.co.nz)

### ISSUE THREAD

**Issue by syrys-lbsoft** [serverless-components/website#39]
so, this component fails to create ssl certificates if the domain a tld that has `.` in it. For example: `.co.nz`

**Here is what happens:**

serverless.yml as per documentation/example
```
component: website
name: some-name
stage: dev

inputs:
  domain: subdomain.example.co.nz
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
```

run: `serverless deploy --debug`

error:
```
...
Checking if a certificate for the co.nz domain exists
Certificate for the co.nz domain does not exist. Creating...
Validating the certificate for the co.nz domain.

 TypeError: Cannot read property 'Name' of undefined
    at ensureCertificate (/var/task/utils.js:392:51)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Website.deploy (/var/task/serverless.js:59:37)
    at async Runtime.module.exports [as handler] (/opt/nodejs/node_modules/@serverless/
core/handler.js:273:24)
```

When i look at my AWS Certificate Manager, it is trying to create a SSL certificate for `.co.nz` (and `*.co.nz`) rather than `example.co.nz` (and `*.example.co.nz`). In the above scenario, i have `example.co.nz` on my Route53 Hosted Zones. 

I can easily create a certificate manually, is there a way to tell the component to skip ssl certificate creation and simply provide the certificate arn?
