### ISSUE TITLE
Support for multiple environments

### ISSUE THREAD

**Issue by gandatandya** [serverless-components/website#44]
Hello, I am new to the Serverless community. Serverless framework has been awesome for me. I migrated my API(s) successfully completely through Serverless framework tutorial. Now I am migrating my front-end code as well. As I am building my react front-end app using this website component, I stumbled upon how I can configure dev vs prod environment. To be precise, under my /src folder I have appconfig.js file where I have environment variables logic with process.env.NODE_ENV that tells the front-end which endpoint it should go (dev/prod). With Serverless website (Client-side rendering) and static hosting, is there any way I can point my front-end to different API endpoints depending on the stage or some other variables? If not, will this feature be added? Thank you for the help in advance!

**Comment by eahefnawy** [comment]
Welcome @gandatandya 🙌 

Is this env logic available after the build? The component just takes your `dist` directory and push it to the cloud. So if it's there it should work fine.

**Comment by gandatandya** [comment]
Thanks for the explanation @eahefnawy.

I was able to configure for multiple environments using the following serverless file structures.
Basically I create an env and yml file for each environment and inside the .env files, I am setting the NODE_ENV variables. And it works!

**Comment by eahefnawy** [comment]
Thanks @gandatandya that's good to hear 😊

**Comment by spencer-wegner** [comment]
Hew @gandatandya and @eahefnawy I'm trying to do the same thing: configure my frontend using this component to point to different api urls based on the `NODE_ENV` variable. I have different `.env` files (e.g. `.env.stage`, `.env.prod`) for each environment and I am setting the `NODE_ENV` variable within them. However, none of the environment variables that I put in the `.env` files including the `NODE_ENV` variable are available in my application. It looks like the component is setting `NODE_ENV=production` by default. 

Here's one of my .env files for an environment called stage:
```
# .env.stage
AWS_ACCESS_KEY_ID=XXX
AWS_SECRET_ACCESS_KEY=XXX
DOMAIN=XXX
BUCKET_NAME=XXX
NODE_ENV=staging
```

Here's the `process.env` variable when I console log it:
```
NODE_ENV: "production"
PUBLIC_URL: ""
WDS_SOCKET_HOST: undefined
WDS_SOCKET_PATH: undefined
WDS_SOCKET_PORT: undefined
```

I only have one `serverless.yml` file:
```
component: website@1.0.1
name: XXX
app: XXX

inputs:
  src:
    src: ./src
    hook: yarn build
    dist: ./build
  domain: ${env:DOMAIN}
  region: us-west-2
  bucketName: ${env:BUCKET_NAME}

plugins:
  - serverless-dotenv-plugin
```

Is there a way to inject environment variables under `inputs`? I know this is possible in the express serverless component like this:
```
component: express@1.0.9
...
inputs:
  ...
  env:
     TEST: ${env:TEST}
```

Any ideas of why this isn't working? Thanks!

**Comment by eahefnawy** [comment]
@spencer-wegner how are you running deploy? The relevant env var is loaded based on the stage you're deploying to.

If you run `sls deploy`, this loads `.env` file

If you run` sls deploy --stage prod`, this loads `.env.prod` file

if you run `sls deploy --stage dev`, this loads `.env.dev` file

Other than that, you seem to be referencing the env vars correctly in the `serverless.yml` file. You just don't need that `serverless-dotenv-plugin`. Plugins don't work in components.

**Comment by spencer-wegner** [comment]
@eahefnawy I have been running deploy the way you are describing it. I am still unsuccessful however. I am using Create React App for my build process which does not allow developers to manually change the `NODE_ENV` variable. See [here](https://create-react-app.dev/docs/adding-custom-environment-variables/). I think that even if I define a `NODE_ENV` variable in my `.env` files it is getting overwritten by CRA. 

Let me know if you think setting the `NODE_ENV` variable should be possible despite using CRA. Otherwise I'm just manually adjusting my configuration file depending on my deployment environment. Thanks!

**Comment by Enase** [comment]
Hi @eahefnawy!

I didn't dive deep into your discussion, but I want to share my thoughts about environment in components.

I think there should be a way to pass environment variables from serverless.yml due to the fact that currently everyone **must** define all the variables **manually** by copy/paste all the aws components ids/links/etc. I believe it should be a way to set variables with references to other stacks output or other complex logic like this:
```
component: website
name: XXX
app: XXX

inputs:
  environment:
    AWS_APPSYNC_ENDPOINT: ${cf:${self:provider.stage}-appsync.AppSyncApiUrl}
    VARIABLE_BY_JS: ${file(path/account-id.js):getAccountId}
    OTHER_VARIABLE:
       Fn::ImportValue: sharedValueToImport
```

I hope you understand the main idea and the reason why it's important.
Thanks in advance.
