### ISSUE TITLE
Using variables in definition

### ISSUE THREAD

**Issue by skinofstars** [serverless-components/website#57]
Hey, I'm trying to use variable to declare my domain name, but for some reason I can't seem to get it to work. Here's a simple example that errors

```
custom:
  domain: example.com

inputs:
  domain: ${self:custom.domain}
```

Which returns the error:

`Error: "${self:custom.domain}" is not a valid domain.`

Are variables not available for config?

Thanks
