### ISSUE TITLE
Allow origin configuration on cloudfront

### ISSUE THREAD

**Issue by JoaquinFernandez** [serverless-components/website#62]
Hi,
It would be awesome to allow origin configuration for the cloudfront distribution. It is a common use case when you want to place your API under xxxxxx.yy/api. That way you could use the output from deploying an API (i.e. through express component).

Right now, in serverless service I am able to do this through this cloudformation configuration:

```
            DomainName:
              Fn::Join:
                - ''
                - 
                  - Ref: ApiGatewayRestApi
                  - '.execute-api.${self:provider.region}.amazonaws.com'
            OriginPath: '/${opt:stage}'

```
