### ISSUE TITLE
When deploying command adds cloudfront cname

### ISSUE THREAD

**Issue by Ewan-Roberts** [serverless-components/website#65]
```
Updating CloudFront distribution of ID XXXXXXXX.
Adding "xxxxx.com" certificate to CloudFront distribution
Adding domain "www.xxxxx.com" to CloudFront distribution
Adding domain "xxxxx.com" to CloudFront distribution
```
I dont own the CNAME for www.xxxxx.com so it throws a `InvalidViewerCertificate`

```
component: website
name: landing-page4
stage: dev

inputs:
  domain: 'http://www.xxxxx.com'
  src:
    src: ./src
    hook: npm run build
    dist: ./dist

```
Why is it adding the `www` domain? I cant deploy to live as it stands as its forcing this options. Appreciate some help
