### ISSUE TITLE
Serverless.yml env attribute

### ISSUE THREAD

**Issue by vtr-rivia** [serverless-components/website#80]
I've read the [documents](https://github.com/serverless-components/website/tree/v1#3-configure) and it showed to me and attribute called env. Where are the env.js file after serverless deploy?

I'm using component: website vue-starter

**Comment by vtr-rivia** [comment]
That is my serverless.yml
    
```
org: vtroliveira
app: test
name: front
component: website

inputs:
  env:
    API_URL: ${cf:public-api-${stage}.ServiceEndpoint}
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
```
