### ISSUE TITLE
NuxtJS deploy problems

### ISSUE THREAD

**Issue by vtr-rivia** [serverless-components/website#87]
I've tried to deploy a VueJS project but I'm facing this error

```
Deploying...

 HTTPError: Response code 403 (Forbidden)
    at EventEmitter.<anonymous> (/opt/nodejs/node_modules/@serverless/core/node_modules/got/index.js:482:24)
    at EventEmitter.emit (events.js:314:20)
    at EventEmitter.emit (domain.js:483:12)
    at getResponse (/opt/nodejs/node_modules/@serverless/core/node_modules/got/index.js:320:5)
    at Immediate.<anonymous> (/opt/nodejs/node_modules/@serverless/core/node_modules/got/index.js:147:6)
    at processImmediate (internal/timers.js:461:21)

23s › Serverless › There's a problem with your files and they could not be loaded by this Component.  Original error: Response code 403 (Forbidden)  

  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/
 ```
  
  Here is my serverless.yml content

```
org: aaaaaaa
app: xxxxxxx
name: aaaaaaa
component: website

inputs:
  cloudfront:
    distributionId: ${param:CLOUDFRONT_ID}
  src:
    src: .
    hook: yarn build
    dist: ./dist
```
