### ISSUE TITLE
Allow inputs.src.hook to expand variables

### ISSUE THREAD

**Issue by divillysausages** [serverless-components/website#92]
I have multiple scripts in my `package.json`, such as:

````json
"build-prod": "webpack --env stage='prod'",
"build-staging": "webpack --env stage='staging'"
````

In `serverless.yml`, I can use variables such as `${stage}` for pretty much everything (e.g. `domain`, `bucketName`, etc), EXCEPT for the `hook`

So this works:

````yml
inputs:
  src:
    src: ./src
    hook: npm run build-prod # hook to run before building
    dist: ./.build # output folder
  domain: ${stage}.mydomain.com # domain name
  region: ${env:REGION}
  bucketName: ${stage}.mydomain.com
````

but this doesn't

````yml
inputs:
  src:
    src: ./src
    hook: npm run build-${stage} # hook to run before building
    dist: ./.build # output folder
  domain: ${stage}.mydomain.com # domain name
  region: ${env:REGION}
  bucketName: ${stage}.mydomain.com
````

It would be great if that was possible
