### ISSUE TITLE
The component is not deploying the website

### ISSUE THREAD

**Issue by tahir-mcloud** [serverless-components/website#96]
Hello, I ran into this issue where I wanted to deploy a static website but the initial code itself is not working.

**Issue**: 
- I gave a bucket name but it created some random bucket which had some serverless json files but it wasn't a website enabled bucket.
- It didn't create the cloudfront resources as well.

Here's my config file:

name: api-docs-website                 # (required) name of your website component instance.
stage: dev                       # (optional) serverless dashboard stage. default is dev.

```
inputs:
  component: "@serverless/website"
  code:
    root: ./
    src: ./src                     # (optional) path to the source folder. default is a hello world html file.
    # domain: serverless.com         # (optional) domain name. this could also be a subdomain.
  region: us-east-1             # (optional) aws region to deploy to. default is us-east-1.
  bucketName: api-docs-bucket-28-06-2024       # (optional) aws bucket name. default is an auto generated name.
```
Folder **structure:**
<img width="160" alt="image" src="https://github.com/serverless-components/website/assets/170626831/3e043423-cb33-41ec-9e8d-cd547139b65e">

**Note:** This is the version 1 code, I also tried the latest one, but it's the same
